### ISSUE TITLE
Create contract to manage new namespace

### ISSUE THREAD

**Issue by friedger** [Light-Labs/community-handles#1]
The contract should allow 
- [x] users to register a standard bns name for ryder namespace 
- [x] a fee after KYC is charged for the name
- [x] admins to change the fee
- [x] admins to change the admins

**Comment by louiseivan** [comment]
This is for the proposal for CityCoins but for the general one, it should be the same as stx.name of btc.us.

**Comment by friedger** [comment]
For existing namespaces, no contract is necessary.

**Comment by MarvinJanssen** [comment]
The trick to making this work is by (ab)using the namespace price update feature. But it is paramount that the managing contract is the one to register the namespace.

**Comment by LNow** [comment]
@MarvinJanssen this approach sounds very familiar :wink:

**Comment by friedger** [comment]
Deployed on testnet.
